version: "3.7"

services: 
  two-factor-auth:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - /app/node_modules
      - .:/app
    ports: 
      - 3000:3000
    depends_on: 
      - mongodb
    environment: 
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27077:27077  
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes: 
      - mongodb-data:/data/db
 

  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
      - mongodb   
    ports: 
      - 8083:8083
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD} 
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    volumes:
      - mongodb-data  
    
        
volumes:
  mongodb-data:
    driver: local